use_frameworks!

platform :ios, '8.0'

target 'FakeXinGePush_Example' do
  pod 'FakeXinGePush', :path => '../'

  target 'FakeXinGePush_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
