# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.1

cache: cocoapods

podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version

install:
- pod install --project-directory=Example

before_script:
- echo "orz"

jobs:
  include:
  - stage: check
    script:
    - pod lib lint
  - stage: test
    script:
    - travis_retry set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/FakeXinGePush.xcworkspace -scheme FakeXinGePush-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - stage: publish
    script:
    - pod trunk push FakeXinGePush.podspec
    if: tag IS present

after_script:
- echo "orz"
